In [1]:
## 导入需要的库
import numpy as np
import pandas as pd
import math
import os
import random
from matplotlib.pyplot import *
import matplotlib.pyplot as plt

from statsmodels.stats.weightstats import ztest

# 聚类结果比较

## 我们模型的聚类

In [9]:
## 聚类结果如下所示
lb1 = [20, 1, 4, 5, 6, 9, 16, 22, 25, 34, 36, 38, 43, 44, 46, 49]
lb2 = [12, 17, 27, 2, 3, 8, 10, 21, 23, 24, 26, 29, 30, 31, 33, 37, 47, 48]
lb3 = [0, 7, 11, 13, 14, 15, 18, 19, 28, 32, 35, 39, 40, 41, 42, 45]

## K-means聚类

In [95]:
from sklearn.cluster import KMeans
X = data
estimator = KMeans(n_clusters = 4)#构造聚类器
estimator.fit(X)#聚类
label_pred = estimator.labels_ #获取聚类标签
label_pred

array([3, 0, 3, 3, 1, 1, 3, 1, 3, 3, 3, 3, 3, 3, 1, 1, 3, 2, 1, 0, 3, 0,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 3, 3, 3, 1, 1, 3, 3, 0, 1, 3, 3,
       3, 1, 3, 3, 3, 3])

In [97]:
a1, a2, a3 = [], [], []

for j in range(0,len(df1)):
    if label_pred[j] == 1:
        a1.append(j)
    elif label_pred[j] == 3:
        a2.append(j)
    else:
        a3.append(j)
print(a1)
print(a2)
print(a3)

[4, 5, 7, 14, 15, 18, 31, 32, 36, 37, 41, 45]
[0, 2, 3, 6, 8, 9, 10, 11, 12, 13, 16, 20, 22, 23, 24, 25, 26, 27, 28, 29, 30, 33, 34, 35, 38, 39, 42, 43, 44, 46, 47, 48, 49]
[1, 17, 19, 21, 40]


In [3]:
# 读取结果
df1 = pd.read_excel("K-means聚类结果.xlsx")
df1 = df1.drop(['Unnamed: 0'], axis = 1)
df1.head()

聚类     距离
0   2  6.686
1   2  5.434
2   4  5.693
3   1  4.920
4   2  4.738

In [6]:
A1, A2, A3 = [], [], []

for j in range(0,len(df1)):
    if df1['聚类'][j] == 1:
        A1.append(j)
    elif df1['聚类'][j] == 2:
        A2.append(j)
    else:
        A3.append(j)
print(A1)
print(A2)
print(A3)

[3, 8, 9, 11, 12, 16, 17, 20, 23, 26, 27, 30, 39, 42, 43, 46]
[0, 1, 4, 5, 7, 10, 13, 14, 15, 18, 19, 25, 28, 29, 31, 32, 33, 34, 35, 36, 37, 38, 40, 41, 44, 45, 47, 48, 49]
[2, 6, 21, 22, 24]


In [8]:
## 根据K-means的距离对分类结果进行降序排序
AA1 = sorted(A1, key=lambda x: df1['距离'][A1.index(x)], reverse = True)
AA2 = sorted(A2, key=lambda x: df1['距离'][A2.index(x)], reverse = True)
AA3 = sorted(A3, key=lambda x: df1['距离'][A3.index(x)], reverse = True)
print(AA1)
print(AA2)
print(AA3)

[3, 42, 17, 30, 27, 9, 39, 8, 20, 11, 12, 26, 23, 16, 43, 46]
[0, 47, 34, 36, 29, 45, 48, 13, 25, 19, 4, 28, 41, 44, 1, 40, 33, 37, 14, 5, 49, 7, 18, 15, 35, 10, 31, 32, 38]
[2, 21, 6, 22, 24]


## 三支聚类

In [11]:
data = pd.read_csv("归一化数据.csv")
data = data.drop(['Unnamed: 0'], axis = 1)
data.head()

0         1         2         3         4         5         6  \
0  0.542315  0.631639  0.537692  0.657919  0.425744  0.533389  0.432409   
1  0.447122  0.625455  0.506848  0.492007  0.638708  0.775372  0.466275   
2  0.274827  0.525519  0.597789  0.462946  0.515822  0.387707  0.535493   
3  0.513593  0.519015  0.508134  0.414162  0.502106  0.602256  0.390319   
4  0.582469  0.490905  0.563069  0.358929  0.322298  0.591241  0.684933   

          7         8         9  ...      1490      1491      1492      1493  \
0  0.655109  0.533334  0.454244  ...  0.618472  0.499274  0.496539  0.506831   
1  0.486687  0.521557  0.493482  ...  0.505660  0.553300  0.521557  0.553096   
2  0.275107  0.520282  0.478059  ...  0.616526  0.434512  0.548418  0.433224   
3  0.603137  0.596409  0.702611  ...  0.107530  0.699745  0.002770  0.008172   
4  0.445066  0.304304  0.519341  ...  0.567308  0.608957  0.668854  0.452971   

       1494      1495      1496      1497      1498      1499  
0  0.472601  0.540841  0.522418  0.551274  0.548531  0.472711  
1  0.552896  0.442834  0.441554  0.569715  0.505557  0.521557  
2  0.753095  0.458347  0.570396  0.614078  0.525519  0.761053  
3  0.471095  0.630606  0.550657  0.816108  0.271831  0.147693  
4  0.441484  0.482484  0.503411  0.587869  0.503570  0.556060  

[5 rows x 1500 columns]

In [31]:
### 设定正理想解和负理想解
n, m = len(data), len(data.T)

### 计算决策对象到正负理想解的距离
D1 = np.zeros((1,n));D0 = np.zeros((1,n)); Pr = []
for i in range(0,n):
    D1[0][i] = np.sqrt(np.sum(np.square(1 - data.iloc[i]))) 
    D0[0][i] = np.sqrt(np.sum(np.square(data.iloc[i])))
    Pr.append(D0[0][i]/(D0[0][i] + D1[0][i]))
print(Pr)

[0.5247144771230003, 0.5173275636122036, 0.5218540428181127, 0.5229287540907313, 0.5201564940217025, 0.5243552762323869, 0.5169976292964519, 0.5192734399006849, 0.5210955163661969, 0.5294100021254201, 0.5241471926417713, 0.5201965466748281, 0.5208650973288269, 0.5230395666609178, 0.5232938637622099, 0.5234209835099527, 0.5196034003251124, 0.5213048113175031, 0.5232962696455145, 0.5239544315929255, 0.522286687344883, 0.5111049886100962, 0.5152301326009899, 0.5261079423373131, 0.5206599335632118, 0.5192297981420132, 0.5238042731505617, 0.522841626969787, 0.5199991739923067, 0.5247110333420674, 0.5259971052776624, 0.520137040108017, 0.5281229961655809, 0.5235937549649751, 0.5207489883140904, 0.524895800860432, 0.5245845814387203, 0.5240178685471395, 0.5225417874004746, 0.522216710985837, 0.5215442080177991, 0.5256022595092653, 0.5211182604213543, 0.525395698763866, 0.5221727216517582, 0.5247056480251316, 0.5232949195070825, 0.5217115845222301, 0.5258231101007541, 0.5210375336166605]


In [23]:
def sunshi(x,singam):
    lamda = np.zeros((len(x),6));
    juhe = np.zeros((1,6));
    
    # 计算相对损失函数
    for i in range(0,len(x)):
        lamda[i,1] = singam[i] * x[i];
        lamda[i,2] = x[i];
        lamda[i,3] = 1-x[i];
        lamda[i,4] = singam[i] * (1-x[i]);
    
    # 计算聚合相对效用函数(均值聚合)
    juhe = np.mean(lamda,axis=0)
    
    return juhe

In [27]:
# 计算不同对象的聚合相对损失函数矩阵
singam = [0.45]*m
lamda = np.zeros((n,6));
for i in range(0,n):
    x = data.iloc[i]
    lamda[i] = sunshi(x ,singam)

#根据聚合相对损失函数计算不同对象的初始阈值
yuzhi = np.zeros((n,2))
for i in range(0,n):
    for j in range(0,len(lamda.T)):
        yuzhi[i][0] = (lamda[i][3]-lamda[i][4])/(lamda[i][3]-lamda[i][4]+lamda[i][1])
        yuzhi[i][1] = (lamda[i][4])/(lamda[i][4]+lamda[i][2]-lamda[i][1])
yuzhi = pd.DataFrame(yuzhi)
yuzhi.head()

0         1
0  0.522188  0.422497
1  0.531101  0.431245
2  0.525451  0.425692
3  0.525545  0.425785
4  0.528054  0.428247

In [107]:
B1, B2, B3 = [], [], []
for i in range(n):
    if Pr[i] > yuzhi.loc[i][0]:
        B1.append(i)
    elif Pr[i]> 0.52 and Pr[i] < yuzhi.loc[i][0]:
        B2.append(i)
    else:
        B3.append(i)
print(B1)
print(B2)
print(B3)

[0, 5, 9, 10, 19, 23, 26, 29, 30, 32, 35, 36, 41, 43, 45, 48]
[2, 3, 4, 8, 11, 12, 13, 14, 15, 17, 18, 20, 24, 27, 31, 33, 34, 37, 38, 39, 40, 42, 44, 46, 47, 49]
[1, 6, 7, 16, 21, 22, 25, 28]


## 基于遗憾理论的灰度关联聚类方法

In [34]:
data.head()

0         1         2         3         4         5         6  \
0  0.542315  0.631639  0.537692  0.657919  0.425744  0.533389  0.432409   
1  0.447122  0.625455  0.506848  0.492007  0.638708  0.775372  0.466275   
2  0.274827  0.525519  0.597789  0.462946  0.515822  0.387707  0.535493   
3  0.513593  0.519015  0.508134  0.414162  0.502106  0.602256  0.390319   
4  0.582469  0.490905  0.563069  0.358929  0.322298  0.591241  0.684933   

          7         8         9  ...      1490      1491      1492      1493  \
0  0.655109  0.533334  0.454244  ...  0.618472  0.499274  0.496539  0.506831   
1  0.486687  0.521557  0.493482  ...  0.505660  0.553300  0.521557  0.553096   
2  0.275107  0.520282  0.478059  ...  0.616526  0.434512  0.548418  0.433224   
3  0.603137  0.596409  0.702611  ...  0.107530  0.699745  0.002770  0.008172   
4  0.445066  0.304304  0.519341  ...  0.567308  0.608957  0.668854  0.452971   

       1494      1495      1496      1497      1498      1499  
0  0.472601  0.540841  0.522418  0.551274  0.548531  0.472711  
1  0.552896  0.442834  0.441554  0.569715  0.505557  0.521557  
2  0.753095  0.458347  0.570396  0.614078  0.525519  0.761053  
3  0.471095  0.630606  0.550657  0.816108  0.271831  0.147693  
4  0.441484  0.482484  0.503411  0.587869  0.503570  0.556060  

[5 rows x 1500 columns]

In [40]:
r1 = np.zeros((n,m))
r2 = np.zeros((n,m))

for i in range(n):
    for j in range(m):
        r1[i][j] = 1/(1.5-data.loc[i][j])
        r2[i][j] = 1/(data.loc[i][j]+0.5)
print(r1)

[[1.04418521 1.1515943  1.03916813 ... 1.05404535 1.05100659 0.97343615]
 [0.94977734 1.14345112 1.00689561 ... 1.07493958 1.00558793 1.02203216]
 [0.81621121 1.02618747 1.10838819 ... 1.12876782 1.02618747 1.35327622]
 ...
 [0.91934393 0.86993345 0.94859569 ... 1.04374976 1.02637481 0.99329448]
 [1.0674121  1.01281321 1.03935724 ... 1.0372851  1.06067791 0.95274409]
 [1.32265622 1.0355309  1.00112996 ... 1.05558676 1.05540027 1.05520034]]


In [41]:
print(r2)

[[0.95940242 0.88367432 0.96367726 ... 0.9512266  0.95371508 1.02805431]
 [1.05583059 0.8885299  0.99319819 ... 0.9348283  0.99447383 0.97889769]
 [1.29061079 0.97511583 0.91092185 ... 0.89760305 0.97511583 0.79298836]
 ...
 [1.09616936 1.17579722 1.0572947  ... 0.95977032 0.97494674 1.00679667]
 [0.94059688 0.98750694 0.96351468 ... 0.96530232 0.9458888  1.05218832]
 [0.80389365 0.96682647 0.99887258 ... 0.94997472 0.95012582 0.95028791]]


In [50]:
# 建立感知效用矩阵
def Juzhen(alpha, sigma):
    U = np.zeros((n,m))
    R = r1/(r1+r2)
    G = 1 - np.exp(sigma * abs(r1-1))
    Q = 1 - np.exp(-sigma * abs(r1-1))
    for i in range(n):
        for j in range(m):
            U[i][j] = (R[i][j]) ** alpha + G[i][j] + Q[i][j] 
    return U

In [55]:
U = Juzhen(0.5,0.15)
U

array([[0.72186863, 0.75169253, 0.72027507, ..., 0.72494263, 0.72400333,
        0.69737614],
       [0.6881008 , 0.74968847, 0.70952285, ..., 0.73121322, 0.70906801,
        0.71467685],
       [0.62166541, 0.71605691, 0.74060982, ..., 0.74597744, 0.71605691,
        0.7912481 ],
       ...,
       [0.67523048, 0.65172624, 0.68762147, ..., 0.72173112, 0.71611878,
        0.70471496],
       [0.72899127, 0.71156187, 0.72033551, ..., 0.71967175, 0.7269683 ,
        0.68929735],
       [0.78630967, 0.71910711, 0.70750569, ..., 0.72541638, 0.72535916,
        0.72529778]])

In [74]:
# 计算聚类系数
u = []
w = [0.1,0.2,0.5,0.05,0.15]
for i in range(n):
    u.append(np.sum(w * U[i][m-5:]))
print(u)

[0.7184094115870056, 0.7141274215153399, 0.742986150628281, 0.7394346505303686, 0.7248104206450712, 0.724600956371658, 0.7343808201283915, 0.7169338617510745, 0.710432583239896, 0.7287695650471153, 0.7202955672152969, 0.7351618044046676, 0.7074098742877456, 0.7172302037222631, 0.7076862981704696, 0.7111561637104268, 0.7057585356634888, 0.7179503963215538, 0.7754113218680725, 0.7583042975436832, 0.7039580854040194, 0.7391830568378985, 0.7136373483403715, 0.7347163110612236, 0.7236110331134162, 0.7219439537678026, 0.7175250437847478, 0.7216385745646728, 0.7145409821710145, 0.7181929887785922, 0.7349301121815097, 0.7246337168540274, 0.739816037940677, 0.7313469491200347, 0.7163305663872453, 0.7260124109873113, 0.7244592048103091, 0.7311488887651453, 0.7776454513805113, 0.7215877370053849, 0.719505237011091, 0.7350589428382549, 0.7190942399659654, 0.7191226197055798, 0.719279859660946, 0.7164332884118563, 0.7455535637787117, 0.7149411107223523, 0.7067492638604718, 0.7213212048612319]


In [77]:
C1, C2 = [], []
for i in range(n):
    if u[i] > np.mean(u):
        C1.append(i)
    else:
        C2.append(i)
print(C1)
print(C2)

[2, 3, 6, 9, 11, 18, 19, 21, 23, 30, 32, 33, 35, 37, 38, 41, 46]
[0, 1, 4, 5, 7, 8, 10, 12, 13, 14, 15, 16, 17, 20, 22, 24, 25, 26, 27, 28, 29, 31, 34, 36, 39, 40, 42, 43, 44, 45, 47, 48, 49]


# 亲和传播聚类算法

In [87]:
from numpy import unique
from sklearn.cluster import AffinityPropagation
import numpy as np
from sklearn.preprocessing import StandardScaler

# 定义数据集
X = data
X = StandardScaler().fit_transform(X)
# 定义模型
model = AffinityPropagation(damping=0.5, max_iter=200, convergence_iter=15, copy=True, preference=None,    
                            affinity='euclidean', verbose=False) # 设置damping : 阻尼系数，取值[0.5,1)
# 匹配模型
model.fit(X)
yhat = model.predict(X)  # yhat为集群结果
clusters = len(unique(yhat))  # 类别

print(yhat)

[2 2 0 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 2 2 2 2 4 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [89]:
D1, D2 = [], []
for i in range(n):
    if yhat[i] == 2:
        D1.append(i)
    else:
        D2.append(i)
print(D1)
print(D2)

[0, 1, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 23, 24, 25, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
[2, 6, 21, 26]


## 逆协方差聚类

In [121]:
# 计算协方差
V = np.zeros((n,n))
for i in range(n):
    for j in range(n):
        V[i][j] = np.min(np.corrcoef(data.iloc[i],data.iloc[j]))
# 计算逆协方差
V1 = np.linalg.inv(V)
V1

array([[ 1.16110418, -0.02178836,  0.02177256, ..., -0.05185477,
         0.0046179 ,  0.04004013],
       [-0.02178836,  1.34878479, -0.02804052, ...,  0.03025174,
         0.01338198, -0.10955989],
       [ 0.02177256, -0.02804052,  1.07145197, ..., -0.00407898,
        -0.0105468 , -0.03383975],
       ...,
       [-0.05185477,  0.03025174, -0.00407898, ...,  1.11168866,
         0.00839435, -0.02809253],
       [ 0.0046179 ,  0.01338198, -0.0105468 , ...,  0.00839435,
         1.76570411, -0.04165954],
       [ 0.04004013, -0.10955989, -0.03383975, ..., -0.02809253,
        -0.04165954,  1.15815236]])

In [123]:
V2 = pd.DataFrame(V1)
V2.head()

0         1         2         3         4         5         6   \
0  1.161104 -0.021788  0.021773 -0.050714 -0.021149 -0.071198  0.045942   
1 -0.021788  1.348785 -0.028041 -0.014223 -0.006008 -0.118318 -0.018628   
2  0.021773 -0.028041  1.071452 -0.069107 -0.075525 -0.041728 -0.144229   
3 -0.050714 -0.014223 -0.069107  1.110317  0.002581  0.093539 -0.052857   
4 -0.021149 -0.006008 -0.075525  0.002581  1.835695 -0.033087  0.043784   

         7         8         9   ...        40        41        42        43  \
0  0.036318 -0.042254 -0.019836  ... -0.128461 -0.039158 -0.077559 -0.002576   
1  0.001795  0.014060  0.033023  ... -0.281291  0.088593 -0.107485 -0.015210   
2  0.008880  0.019423 -0.041145  ... -0.002259  0.011930 -0.017409 -0.027165   
3 -0.021516 -0.046649 -0.099926  ... -0.022581  0.037681 -0.049769  0.013739   
4 -0.232154 -0.056897  0.029144  ...  0.015337 -0.075858  0.054003 -0.007447   

         44        45        46        47        48        49  
0 -0.035363  0.009199 -0.031333 -0.051855  0.004618  0.040040  
1 -0.055786 -0.008822 -0.008065  0.030252  0.013382 -0.109560  
2 -0.001649 -0.008774 -0.039272 -0.004079 -0.010547 -0.033840  
3  0.014416  0.048504 -0.036481 -0.048535 -0.025484 -0.071280  
4 -0.008449 -0.168782  0.051203 -0.005344  0.021078 -0.046123  

[5 rows x 50 columns]

In [128]:
l = np.random.randint(0,49)
print(l)
E1, E2 = [], []
for i in range(n):
    if V2.loc[l][i]>0:
        E1.append(i)
    else:
        E2.append(i)
print(E1)
print(E2)

2
[0, 2, 7, 8, 10, 14, 15, 18, 19, 20, 23, 24, 25, 28, 30, 31, 32, 34, 36, 37, 38, 41]
[1, 3, 4, 5, 6, 9, 11, 12, 13, 16, 17, 21, 22, 26, 27, 29, 33, 35, 39, 40, 42, 43, 44, 45, 46, 47, 48, 49]


In [101]:
def getEuclidean(point1, point2):
    dimension = len(point1)
    dist = 0.0
    for i in range(dimension):
        dist += (point1[i] - point2[i]) ** 2
    return math.sqrt(dist)

In [105]:
dist = np.zeros((n,n))
for i in range(n):
    for j in range(n):
        dist[i][j] = getEuclidean(data.iloc[i], data.iloc[j])
dist

array([[0.        , 8.63204257, 9.83432789, ..., 8.75984001, 8.98484261,
        8.85576706],
       [8.63204257, 0.        , 9.01366568, ..., 8.21125272, 8.07301829,
        7.37650012],
       [9.83432789, 9.01366568, 0.        , ..., 9.09539412, 9.2046212 ,
        8.74564117],
       ...,
       [8.75984001, 8.21125272, 9.09539412, ..., 0.        , 8.50656396,
        8.00844539],
       [8.98484261, 8.07301829, 9.2046212 , ..., 8.50656396, 0.        ,
        7.81675047],
       [8.85576706, 7.37650012, 8.74564117, ..., 8.00844539, 7.81675047,
        0.        ]])